name: questions_by_ottaa
description: A great multimodal communication tool, ask Questions orally and get answered in Pictos
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"
dependencies:
  get: ^4.3.8
  responsive_sizer: 3.0.4+4
  avatar_glow: ^2.0.2
  cupertino_icons: ^1.0.2
  popup_card: ^0.1.0
  
  quiver: ^3.0.1+1

  speech_to_text: ^5.3.0
  flutter_tts: ^3.2.2
  diacritic: ^0.1.3
  sound_stream: ^0.3.0
  rxdart: ^0.27.3
  audioplayers: ^0.20.1
  dialog_flowtter: ^0.3.1
  firebase_core: ^1.10.5
  firebase_database: ^9.0.3
  google_fonts: ^2.1.0
  google_sign_in: ^5.2.1
  google_speech: ^2.0.1 # for androids 
  
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - images/
    - assets/dialog_flow_auth.json
    - assets/
    - assets/.env
    - assets/images/
