name: questions_by_ottaa
description: A great multimodal communication tool, ask Questions orally and get answered in Pictos
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  responsive_sizer: ^3.1.1
  avatar_glow: ^2.0.2
  cupertino_icons: ^1.0.2
  popup_card: ^0.1.0
  quiver: ^3.0.1+1
  speech_to_text: ^6.0.0
  flutter_tts: ^3.2.2
  diacritic: ^0.1.3
  sound_stream:
    git:
      url: https://github.com/satymshrma/flutter-sound-stream.git
      ref: patch-1
  audioplayers: ^1.0.1
  dialog_flowtter: ^0.3.1
  firebase_core: ^1.10.5
  firebase_database: ^9.0.3
  google_fonts: ^3.0.1
  google_sign_in: ^5.2.1
  google_speech: ^2.0.1
  flutter:
    sdk: flutter
  firebase_auth: ^3.9.0
  flutter_dotenv: ^5.0.2
  picto_widget: ^0.0.4
  flutter_riverpod: ^1.0.4
  go_router: ^5.0.1
  either_dart: ^0.2.0
  get_it: ^7.2.0
  rxdart: ^0.27.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/dialog_flow_auth.json
    - assets/
    - dotenv
    - assets/images/
