// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYckwyYFjys6DlADmLko462F47eaXBkX0',
    appId: '1:122497661206:web:a8c8094bd59ca40ca1f837',
    messagingSenderId: '122497661206',
    projectId: 'questions-abd23',
    authDomain: 'questions-abd23.firebaseapp.com',
    databaseURL: 'https://questions-abd23-default-rtdb.firebaseio.com',
    storageBucket: 'questions-abd23.appspot.com',
    measurementId: 'G-RMQ677H96F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAF4P6TDwI1KAs0dG_kO4dFsrt2apT699k',
    appId: '1:122497661206:android:489d0a7519eb5476a1f837',
    messagingSenderId: '122497661206',
    projectId: 'questions-abd23',
    databaseURL: 'https://questions-abd23-default-rtdb.firebaseio.com',
    storageBucket: 'questions-abd23.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDyfLHo5Mq6M4vrmMIURTAgHoSmjHUrgos',
    appId: '1:122497661206:ios:5098015445aff38ca1f837',
    messagingSenderId: '122497661206',
    projectId: 'questions-abd23',
    databaseURL: 'https://questions-abd23-default-rtdb.firebaseio.com',
    storageBucket: 'questions-abd23.appspot.com',
    androidClientId: '122497661206-2ruamubbn0v4q77joh54chrri67016of.apps.googleusercontent.com',
    iosClientId: '122497661206-4hll8mhbvi86mf6vcr9p9mtk2el77b4b.apps.googleusercontent.com',
    iosBundleId: 'com.example.questionsByOttaa',
  );
}
